"""Initial tables

Revision ID: 8d61c9a619ad
Revises: 4521c22db39a
Create Date: 2026-10-07 14:00:13.505070

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d61c9a619ad'
down_revision: Union[str, Sequence[str], None] = '4521c22db39a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('temperatures', sa.Column('date_time', sa.DateTime(), nullable=False))
    op.alter_column('temperatures', 'temperature',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('temperatures', 'temperature',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_column('temperatures', 'date_time')
    # ### end Alembic commands ###
